### ISSUE TITLE
Unable to compile the MaterialExplorer

### ISSUE THREAD

**Issue by Leva7** [material-native/material-native#32]
What I did first:
1) Clone the repository
2) Try `npm install`

Got this error:
```Error: Cannot find module '/home/leva7/material-native/examples/MaterialExplorer/node_modules/react-native/local-cli/cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Then I tried this:
1) Clone the repository (fresh clone)
2) Install `react-native-vector-icons` and `material-native`

NPM logged the following:
```...
├── UNMET PEER DEPENDENCY react-native@>= 0.40
└── UNMET PEER DEPENDENCY react-native-vector-icons@>= 4.0.0
```

3) Then I manually installed both of these through NPM

Another dependency turned out to be missing (so I installed it too)
```UNMET PEER DEPENDENCY react@16.0.0-alpha.12```

After all that, I ran `npm start` and this error popped up:
```
Error: Cannot find module 'react-native/packager/blacklist'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/leva7/material-native/rn-cli.config.js:11:19)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/leva7/material-native/examples/MaterialExplorer/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

So what's the deal with it? I got confused by the fact that there were **absolutely no** dependencies in the MaterialExplorer's `package.json`

**Comment by jpaas** [comment]
For what its worth I cloned the repo yesterday. Ran `yarn` and `react-native run-ios` and it worked.

**Comment by Leva7** [comment]
@jpaas true, seems to work fine now
